# Generated by Django 2.2.16 on 2023-03-17 15:22

from django.db import migrations


def transfer_pub_date_to_created(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        post.created = post.pub_date
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_created'),
    ]

    operations = [
        migrations.RunPython(transfer_pub_date_to_created),
    ]
